config/routes.rb
Rails.application.routes.draw do
  
  resources :genres
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #get "movies" => "movies#index" #as: movie
  #get "movies/:id" => "movies#show", as: "movie"
  #get "movies/:id/edit" => "movies#edit", as: "edit_movie"
  #patch "movies/:id" => "movies#update"

  resources :movies
  root "movies#index"

  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :users 
  get "signup" => "users#new"
  
  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies
  
end

app/models/genre.rb
class Genre < ApplicationRecord

    before_save :set_slug

    has_many :characterizations, dependent: :destroy
    has_many :movies, through: :characterizations

    validates :name, uniqueness: true, presence: true

    def to_param
        slug
    end
    
    private
    def set_slug
        self.slug =  name.parameterize
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
    
    before_action :require_admin
    before_action :set_genre, except: [:index, :new, :create]

    def index
        @genres = Genre.order(:name)
    end
    def new
        @genre = Genre.new
    end
    def create
        @genre = Genre.create(genre_params)
        if @genre.save 
            redirect_to @genre, notice: "Genre succesfully created!"
        else
            render :new
        end
    end
    def destroy
        @genre.destroy
        redirect_to genres_path, alert: "Genre succesfully deleted"
    end
    def edit
        @movies = Movie.all
    end
    def update
        if @genre.update(genre_params)
            redirect_to @genre, notice: "#{@genre.name} genre succesfully updated!"
        else
            render :new
        end
    end
    def show
        @movies = genres(@genre)
    end
    
    private
    def get_image_from_movie_for_genre(genre)
        selected_movie = genre.movie_ids.sample
        movie = Movie.find(selected_movie)
        movie.image_file_name
    end
    def genres(genre)
        movies = Movie.order(:title)
        genre_movies = Array.new
        movies.each do |movie|
            if movie.genres.include?(genre)
                genre_movies << movie 
            end
        end
        genre_movies
    end
    def genre_params
        params.require(:genre).permit(:name, movie_ids: [])
    end
    def set_genre
        @genre = Genre.find_by!(slug: params[:id])
    end

    helper_method :get_image_from_movie_for_genre
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: @genre, local: true) do |f| %>
    
    <%= render "shared/errors", object: @genre %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <div class="checkboxes">
        <%= f.collection_check_boxes(:movie_ids, Movie.order(:name), :id, :title) %>
    </div>
    <%= f.submit %>
<% end %>

app/views/genres/edit.html.erb
<h2>Edit <%= @genre.name %> genre </h2>

<%= render "form", model: @genre %>

app/views/genres/index.html.erb
<h2>Admin movie genres</h2>

<ul class="reviews">
    <% @genres.each do |genre| %>
    <section class="movie">
        <div class="image">
            <%= image_tag get_image_from_movie_for_genre(genre) %>
        </div>
        <div class="summary">
            <h4> <%= link_to genre.name,  genre_path(genre) %> </h4>
            <span class="date">
                <%= genre.movies.size %> movies 
            </span>
            <!--
            <% if current_user_admin?%>
                <p>
                    <%= link_to "Edit", edit_genre_path(genre), class: "button" %>
                    <%= link_to "Delete", genre_path(genre), method: :delete, class: "button", data: {confirm: "Are you sure?"} %>
                </p>
            <% end%>
            -->
        </div>
    </section>
    <% end %>
<ul>

<section class="admin">
    <%= link_to "New gender", new_genre_path, class: "button" %>
</section>

app/views/genres/new.html.erb
<h2>Create a new genre</h2>

<%= render "form", model: @genre %>

app/views/genres/show.html.erb
<h1> <%= @genre.name %> movies </h1>
 <% @movies.each do |movie| %>
    <section class="movie">
        <div class="image">
            <%= image_tag movie.image_file_name %>
        </div>
        <div class="summary">
            <h2> <%= link_to movie.title, movie_path(movie) %> </h2>
            <h3> <%= total_gross(movie) %> </h3>
            <p> <%= truncate(movie.description, length: 150, separator: ' ') %>
        </div>
    </section>
<% end %>
<% if current_user_admin? %>
    <section class="admin">
        <%= link_to "Edit", edit_genre_path(@genre), class: "button" %>
        <%= link_to "Delete", genre_path(@genre), method: :delete, class: "button" %>
    </section>
<% end %>