config/routes.rb
Rails.application.routes.draw do
  
  resources :genres
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #get "movies" => "movies#index" #as: movie
  #get "movies/:id" => "movies#show", as: "movie"
  #get "movies/:id/edit" => "movies#edit", as: "edit_movie"
  #patch "movies/:id" => "movies#update"

  resources :movies
  root "movies#index"

  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :users 
  get "signup" => "users#new"
  
  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies
  
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
Copyright &copy; 2005-<%= Time.now.year %>
<%= link_to 'The Pragmatic Studio', 'https://pragmaticstudio.com' %>

app/views/layouts/_header.html.erb
<nav>
    <%= image_as_link_or_not %>
    <ul class="left">
        <li>
          <%= nav_link_to "Released", movies_path %>
        </li>
        <li>
          <%= nav_link_to "Hits", filtered_movies_path(:hits) %>
        </li>
        <li>
          <%= nav_link_to "Upcoming", filtered_movies_path(:upcoming) %>
        </li>
    </ul>
    <ul class="right">
        <% if current_user %>
          <li>
              <%= link_to current_user.name, current_user %> 
          </li>
          <li>
            <%= link_to "Account settings", edit_user_path(current_user), class: "button" %>
          </li>
          <li>
            <%= link_to "Sign out", session_path, method: :delete, class: "button" %>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign in", signin_path, class: "button" %>
          </li>
          <li>
            <%= link_to "Sign up", signup_path, class: "button" %>
          </li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Súper-Heroic Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <div class ="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
    <footer><p> 
      <%= render "layouts/footer" %>
    </p></footer>
  </body>
</html>